# Generated by Django 3.1 on 2020-08-23 18:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_scrapper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMoviesWatchlist',
            new_name='UserWatchlistMovies',
        ),
    ]
